Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -42,13 +42,13 @@ jobs:
         run: dotnet test LeetCode.Tests/LeetCode.Tests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='./results/'
       - name: Check Coverage Threshold
         run: |
-        coverage=$(grep -Po 'Total\s+\|\s+\K\d+\.\d+(?=%)' ./LeetCode.Tests/results/coverage.info)
-        threshold=90
-          echo "Coverage: $coverage% / $threshold%"
-        if (( $(echo "$coverage < $threshold" | bc -l) )); then
-          echo "Coverage of $coverage% is below the required threshold of $threshold%"
-          exit 1
-        fi
+          coverage=$(grep -Po 'Total\s+\|\s+\K\d+\.\d+(?=%)' ./LeetCode.Tests/results/coverage.info)
+          threshold=90
+            echo "Coverage: $coverage% / $threshold%"
+          if (( $(echo "$coverage < $threshold" | bc -l) )); then
+            echo "Coverage of $coverage% is below the required threshold of $threshold%"
+            exit 1
+          fi
 
   upload-coverage:
     needs: test-with-coverage
